### ISSUE TITLE
How to create a new node?

### ISSUE THREAD

**Issue by xix-xeaon** [godot-nim/gdext-nim#106]
In GDScript it would be:
```
var node = Node3D.new()
```

**Comment by panno8M** [comment]
We have `instantiate(typedesc)` proc.

```nim
var myObject: Object = instantiate Object

# If the type being instantiated is a derivative of RefCounted, the gdref T type is enforced.
var myRefCounted: gdref RefCounted = instantiate RefCounted

# For Node derived types, a template is defined that allows naming at the same time.
var myNode: Node = instantiate(Node, "NewName")
# Of course, it is not always necessary to name them.
var myNode2: Node = instantiate Node
```

I thought about following godot and using the name new, but I thought it would be nonsense to duplicate the name with Nim's core functionality, so I used instantiate.

**Comment by xix-xeaon** [comment]
Alright! But what about things like SurfaceTool?
```nim
var st = instantiate SurfaceTool
st.begin(primitiveTriangles)
```
gives me `type mismatch` because `begin` expects plain `SurfaceTool`, not `GdRef[classindex.SurfaceTool]`.

**Comment by panno8M** [comment]
That's right. Furthermore, the type of the first argument is always designed to be raw.

<details><summary>Why?</summary>

This is to call the base class methods naturally. Nim has the constraint that you cannot convert GdRef[Resource] to GdRef[RefCounted] for instance.
If the first argument is of type GdRef, the parent's function cannot be called straightforwardly.
</details>

Since we have a `[]` accessor, we can extract the contents as follows:

```nim
var st: gdref SurfaceTool = instantiate SurfaceTool
st[].begin(primitiveTriangles)
```

This looks ugly, but is unavoidable as we have to use our gdref instead of Nim's ref.

**Comment by xix-xeaon** [comment]
I don't know if this is a good idea in general, but it seems to work:
```nim
converter deref[T](a :GdRef[T]) :T = a[]
```

**Comment by panno8M** [comment]
I have tried it too. But this still has the drawback of not being able to call methods of the base class. Try the following example.

```nim
import gdext
import gdext/classes/[ gdResource ]
converter deref[T](a :GdRef[T]) :T = a[]

let res: gdref Resource = instantiate Resource
echo res.getReferenceCount()
```
```
type mismatch

Expression: getReferenceCount(res)
[1] res: GdRef[classindex.Resource]
Expected one of (first mismatch at [position]):
[1] proc getReferenceCount(self: RefCounted): int32
```
