### ISSUE TITLE
How to convert seq[T] to Variant?

### ISSUE THREAD

**Issue by hotaru-kirano** [godot-nim/gdext-nim#98]

**Comment by panno8M** [comment]
Please try follows:
```nim
proc gdarray*[T](s: openArray[T]): Array =
  result = gdarray()
  discard result.resize(s.len)
  for i, v in s:
    result[i] = variant v

var myvariant = variant gdarray [1, 2, 3]
```

It does not support direct conversion from seq[T] to Variant, because to implement this, all the data from seq must be copied to Godot.Array.

You must explicitly convert from seq to Array and from Array to Variant.

The seq to Array conversion was not yet implemented, but I saw this issue and thought it was necessary, so I will push it to main later.

Thank you,

**Comment by hotaru-kirano** [comment]
Your array function works. But when it try to convert a table like
```
proc gddict*[K,V](t:Table[K,V]): Dictionary =
    var dict = dictionary()
    for k,v in t:
        echo k,":",v
        dict[k.variant] = v.variant
    dict

proc picfind(s:string): Variant {.gdsync.} =
    # variant gdarray @[s]
    variant gddict {"a": 1, "b": 2}.toTable
```
it crashes with
```
Fatal glibc error: malloc.c:2599 (sysmalloc): assertion failed: (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)
```
Any idea what I'm doing wrong.

Thanks again for your amazing work.

**Comment by hotaru-kirano** [comment]
Actually, converting `dictionary()` to `variant` before putting elements in it fixes it.
Is that intended behavior?

**Comment by panno8M** [comment]
Thanks for the report. It is a bug in the library and has been fixed now.
You can use Dictionary as is if you update your package.

**Comment by hotaru-kirano** [comment]
It's all good now. Cheers.
